version: '3.6'

services:
  db:
    image: postgres
    container_name: ${APP_NAME}_DB
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - ${DB_PORT}:5432
    restart: always

  redis:
    image: redis
    restart: always
    container_name: ${APP_NAME}_REDIS
    ports:
      - ${REDIS_HOST}:6379

  adminer:
    image: adminer
    container_name: ${APP_NAME}_ADMIN
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
    depends_on:
      - db
